# -*- coding: utf-8 -*-
"""Task1-DS26.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X832auV2fykKqWbH-rR8FcCTEpTD-YpY
"""

def register():
    database = open("database.txt", "r")
    email_id = input("enter email_id :")
    Password = input("enter password:")
    Password1= input("confirm password")
    d = []
    f = []
    for i in database:
      a,b= i.split(", ")
      b = b.strip()
      d.append(a)
      f.append(b)
      data = dict(zip(d, f))
      print(data)

    if email_id.endswith("@gmail.com")  == True:
     print(" valid email id")
    else:
     print("not valid email id")
    if Password != Password1:
     print("password not match,restart")
     register()
    else:
     if len(Password)<=6:
        print("password too short:")
        register()
     elif email_id in database :
          print("username exist:")
          register()
     else:
          database = open("database.txt","a")
          database.write(email_id+","+Password+"\n")
          print("done")  
register()          

def access ():
  email_id = input("enter your email_id")
  Password = input("enter your password")
  if not len(email_id or Password)<1:
     d = []
     f = []
     for i in database:
      a,b= i.split(", ")
      b = b.strip()
      d.append(a)
      f.append(b)
      data = dict(zip(d, f))
    
     try:

       if data[email_id]:
        try:
          if Password == data[email_id]:
             print("login success")
             print("welcome",email_id)
          else:
             print("email_id or Password incorrect")
        except:
             print("incorrect email_id and Pasword")
       else:
        print("username does not exist")
     except:
        print("Login error")
  else:
     print("Please enter valid values")

def home(option= None):
	print("Welcome, please select an option")
	option = input("Login | Signup:")
	if option == "Login":
	   access()
	elif option == "Signup":
		 register()
	else:
		print("Please enter a valid parameter, this is case-sensitive")                           

home()

